workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      flutter: stable
    scripts:
      - name: Build iOS
        script: |
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa