workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install pods
        script: | 
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa